import { Metadata } from "next";
import { EB_Garamond, Miriam_Libre } from "next/font/google";
import "./globals.css";

const miriamLibre = Miriam_Libre({
  weight: ["400", "700"],
  style: "normal",
  subsets: ["latin"],
  preload: true,
});
const ebGaramond = EB_Garamond({
  weight: ["400", "700"],
  style: "normal",
  subsets: ["latin"],
  preload: true,
  variable: "--font-eb-garamond",
});

export const metadata: Metadata = {
  title: "Rara Minds",
  description: "Generated by create next giga",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/brain-128.ico",
        href: "/brain-128.ico",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/brain-128.ico",
        href: "/brain-128.ico",
      },
    ],
    apple: "/brain-128.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, viewport-fit=cover"
      />

      <body
        className={`antialiased ${miriamLibre.className} ${ebGaramond.variable}`}
        style={{
          background: "#E6E5E3",
          // backgroundRepeat: "no-repeat",
          // backgroundAttachment: "fixed",
          // backgroundSize: "cover",
          // minHeight: "100vh",
        }}
      >
        {children}
      </body>
    </html>
  );
}
