import { Metadata } from "next";
import { EB_Garamond, Miriam_Libre } from "next/font/google";
import "./globals.css";

const miriamLibre = Miriam_Libre({
  weight: ["400", "700"],
  style: "normal",
  subsets: ["latin"],
  preload: true,
});
const ebGaramond = EB_Garamond({
  weight: ["400", "700"],
  style: "normal",
  subsets: ["latin"],
  preload: true,
  variable: "--font-eb-garamond",
});

export const metadata: Metadata = {
  title: "CV Manager",
  description: "Generated by create next giga",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${miriamLibre.className} ${ebGaramond.variable}`}
        style={{
          background: "linear-gradient(180deg, #E4D9CB 0%, #F9F9F9 27.7%)",
          backgroundRepeat: "no-repeat",
          backgroundAttachment: "fixed",
          backgroundSize: "cover",
          minHeight: "100vh",
        }}
      >
        {children}
      </body>
    </html>
  );
}
